default_stages: [commit]

exclude: (.*\.patch)

repos:
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 5.1.0.1
    hooks:
      - id: buildifier
        args:
          - &buildifier_args "--warnings=native-cc,native-py,out-of-order-load"
      - id: buildifier
        name: "buildifier (external build files)"
        files: &buildifier_external_files ^(.*/)?\w+\.BUILD.bazel$
        args: &buildifier_external_args
          - *buildifier_args
          - --type=build
      - id: buildifier-lint
        args:
          - *buildifier_args
      - id: buildifier-lint
        name: "buildifier-lint (external build files)"
        files: *buildifier_external_files
        args: *buildifier_external_args
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: double-quote-string-fixer
        types: [python]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        args: [-i, --style, .style.yapf]
  - repo: https://github.com/myint/autoflake.git
    rev: v1.5.3
    hooks:
      - id: autoflake
        args: [--remove-all-unused-imports, --ignore-init-module-imports, --in-place]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.2
    hooks:
      - id: reorder-python-imports
        args: [--py37-plus]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
    - id: clang-format
  - repo: https://github.com/cpplint/cpplint
    rev: 1.6.1
    hooks:
      - id: cpplint
        args: ["--filter=-build/c++11,-build/c++14"]
